# Generated by Django 5.1.7 on 2025-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('task_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('task_duration', models.DurationField(blank=True, null=True)),
                ('task_comment', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('p', 'Production'), ('n', 'Non_production')], default='p', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('w', 'Waiting'), ('s', 'Started'), ('p', 'Paused'), ('c', 'Completed')], default='w', max_length=1)),
            ],
        ),
    ]
