# Generated by Django 5.1.7 on 2025-03-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_alter_comment_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
