# Generated by Django 5.1.7 on 2025-03-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0006_alter_comment_options_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_comment',
        ),
    ]
