# Generated by Django 5.1.7 on 2025-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0007_remove_task_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
