# Generated by Django 5.1.7 on 2025-03-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0008_task_task_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task_tracker.task'),
        ),
    ]
