# Generated by Django 5.1.7 on 2025-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0009_remove_task_task_comment_alter_comment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'Waiting'), ('s', 'Started'), ('p', 'Paused'), ('c', 'Completed')], default='w', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('p', 'Production'), ('n', 'Non-production')], default='p', max_length=1, null=True),
        ),
    ]
