# Generated by Django 5.1.7 on 2025-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0011_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(blank=True, choices=[('p', 'Prod'), ('n', 'Non-prod')], default='p', max_length=1, null=True),
        ),
    ]
